name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build Angular
        working-directory: ./frontend
        run: npm run build -- --base-href=/cv-portfolio/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/dist/frontend/browser
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
